"""empty message

Revision ID: 1b8892897a4f
Revises:
Create Date: 2022-06-28 16:04:58.553749

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1b8892897a4f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("example")
    # ### end Alembic commands ###
