name: Link internal audit service to assessment store service

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  link_dev:
      needs: deploy_dev
      runs-on: ubuntu-latest
      environment: Dev
      steps:
        - name: Apply network policy for assessment store
          uses: citizen-of-planet-earth/cf-cli-action@v2
          with:
            cf_api:      ${{secrets.CF_API}}
            cf_org:      ${{secrets.CF_ORG}}
            cf_space:    ${{secrets.CF_SPACE }}
            cf_username: ${{secrets.CF_USER}}
            cf_password: ${{secrets.CF_PASSWORD}}
            command: add-network-policy funding-service-design-assessment-store-dev --destination-app funding-service-design-audit-dev --protocol tcp --port 8080

  link_test:
      needs: deploy_test
      runs-on: ubuntu-latest
      environment: Test
      steps:
        - name: Apply network policy for assessment store
          uses: citizen-of-planet-earth/cf-cli-action@v2
          with:
            cf_api:      ${{secrets.CF_API}}
            cf_org:      ${{secrets.CF_ORG}}
            cf_space:    ${{secrets.CF_SPACE }}
            cf_username: ${{secrets.CF_USER}}
            cf_password: ${{secrets.CF_PASSWORD}}
            command: add-network-policy funding-service-design-assessment-store-test --destination-app funding-service-design-audit-test --protocol tcp --port 8080
